name: torchensemble-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display python version
      run: python -c "import sys; print(sys.version)"
    - name: Install package dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r build_tools/requirements.txt
    - name: Install
      run: pip install --verbose --editable .
    - name: Run tests
      run: |
        pytest --cov-config=.coveragerc --cov-report=xml --cov=torchensemble torchensemble
    - name: Publish code coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
